### ISSUE TITLE
FRQ #1

### ISSUE THREAD

**Issue by sarayu-pr11** [sarayu-pr11/sarayucsa#10]
Implement FRQ1 In Spring Project

- [x] [APCalender](https://github.com/sarayu-pr11/sarayu_spring/blob/master/src/main/java/com/nighthawk/spring_portfolio/mvc/calendar/APCalendar.java)
- [x] [Year.java](https://github.com/sarayu-pr11/sarayu_spring/blob/master/src/main/java/com/nighthawk/spring_portfolio/mvc/calendar/Year.java)

Enhance APIs and @RESTController to work with the all POJOs and APCalendar

- [x] [CalenderAPIController](https://github.com/sarayu-pr11/sarayu_spring/blob/master/src/main/java/com/nighthawk/spring_portfolio/mvc/calendar/CalendarApiController.java)

Test APIs with Browser, Curl, or Postman. Illustrate or show tangibles.

- [x] isLeapYear

![endpoint1](https://user-images.githubusercontent.com/55467797/202653383-e26e4c94-21c8-418c-ba67-59d8a660935b.png)

- [x] firstDayOfYear

![endpoint2](https://user-images.githubusercontent.com/55467797/202653454-b85b4a3e-ee50-4a04-a46d-1e2b8da6a84a.png)

- [x] numberOfLeapYears
![endpoint3](https://user-images.githubusercontent.com/55467797/202653702-27ebb910-1805-486d-ac21-34c93f342b12.png)

- [x] dayOfYear

![endpoint4](https://user-images.githubusercontent.com/55467797/202653477-3cb2fc3e-1925-41c5-b739-7308611d3cc3.png)

- [x] Debug

![debug](https://user-images.githubusercontent.com/55467797/202653493-4a1dc88b-4ec8-42d1-896d-af9fce7ed8fd.png)

**Comment by jm1021** [comment]
2.8
