### ISSUE TITLE
FRQ 2

### ISSUE THREAD

**Issue by sarayu-pr11** [sarayu-pr11/sarayucsa#11]
### Grade: 2.7/3
- [x]  Build Tester Method. Test zero argument and all argument constructor
![image](https://user-images.githubusercontent.com/55467797/204227188-056dec3b-83a6-4b86-883d-56f69ebc205f.png)

- [x] Build other attributes into POJO
![image](https://user-images.githubusercontent.com/55467797/204229491-bf4e5700-f161-4c59-ac4d-0f40f4f2e7f8.png)
![image](https://user-images.githubusercontent.com/55467797/204229551-1711f59c-73af-4fb9-8096-d940a06a637d.png)
![image](https://user-images.githubusercontent.com/55467797/204231041-dccc69a9-9da8-450a-b0e1-53609f321cd4.png)
![image](https://user-images.githubusercontent.com/55467797/204231349-08e5d008-f458-4137-9ccd-88f01af63aa5.png)

- [x] correct the bug in setStats!
![image](https://user-images.githubusercontent.com/55467797/204229917-355015f8-d663-44c1-b22c-f3b993d5162b.png)
![image](https://user-images.githubusercontent.com/55467797/204231681-3346ee20-af6a-4c9a-a324-3d1f87068f18.png)

**Comment by samayasankuratri** [comment]
2.7 did a relevant api controller for the frq like a step counter
