### ISSUE TITLE
Sarayu Final Grading Ticket

### ISSUE THREAD

**Issue by sarayu-pr11** [sarayu-pr11/sarayucsa#16]
### **18.5/20**
18.5/20

| Items                               | Self Score | Pranavi Inukurti | Saumya Palakodety |  Average |
|-------------------------------------|------------|----------|----------|----------|
| N@tM Attendance                     |  1         |  1         | 1         |  1        |
| N@tM Capture the Moment             |  1        | 1         |  1        |  1        |
| Frontend Team Presentation          |  1         |  1        |  1        |  1        |
| Behind the Scenes Team Presentation |   1        |  1        |  1        |  1        |
| Other Team Presentation             |   1        |  1        |  1        | 1         |
| Project Quality                     | 1          | 1         | 1        |  1        |
| UI with Inputs                      | 1          |  1        | 1        |  1        |
| Create and Read                     | 1          | 1         |  1        | 1         |
| Update and Delete                   | 0          | 0        |  0        |  0        |
| Cookies JWT                         | 1          |  1        | 1         |  1        |
| Code Quality                        | 1          | 1         |  1        |  1        |
| Error Handling                      | 1          |  1        | 1         |  1        |
| GET/POST Methods                    | 1          | 1         |  1        |  1        |
| Backend Create/Read                 | 1          |  1        |  1        |   1       |
| Backend Update/Delete               | 1          |  1        | 1         |  1        |
| Purpose/Theme/Quality                     | 0.5        | 0.5                          |     0.5                     |   0.5        |
| Video                                     | 0          | 0                            |    0                      |   0        |
| Runtime Links                             | 0.5        | 0.5                          |   0.5                       |   0.5        |
| README.md                                 | 0.5        | 0.5                          |    0.5                      |   0.5        |
| Blog and Guides for Review                | 0          | 0                            |    0                      |   0        |
| 75% Full Stack                            | 0.5        | 0.5                          | 0.5                         |   0.5        |
| Individual Review Ticket                  | 0.5        | 0.5                          |    0.5                      |  0.5         |
| Runtime Links                             | 0.5        | 0.5                          |    0.5                      |   0.5        |
| Technical Accomplishments                 | 0.5       | 0.5                          |        0.5                  |    0.5       |
| Blog and Guides for Review                | 0       | 0                          |         0                 |    0       |
| Meeting Full Stack and Backend Objectives | 0.5        | 0.5                          |   0.5                       |    0.5       |
| GitHub Analytics                          | 0.5        | 0.5                          |   0.5                       |    0.5       |
Total Table Score: | | | | 18.5/21 |

[Link to Frontend](https://sarayu-pr11.github.io/tri2_pbl/)
[Link to Frontend Repo](https://github.com/sarayu-pr11/tri2_pbl)
[Link to Deployed Backend](https://csatri1.tk)
[Link to Backend Repo](https://github.com/CalrethonOfMirkwood/pbl_backend)
| Night at the Museum | Student Crossover | Silent Review |
|---------------------|-------------------|---------------|
|  ![IMG_5911](https://user-images.githubusercontent.com/55467797/221628598-7d4c5a6c-ef04-4ee6-a6ad-b98759de983e.jpg)  |  Pranavi: 9/10 (DELETE is faulty; doesn't always work)     Saumya: 9/10 (DELETE doesn't always work)  |  Score: 18.5/20  |

**Accomplishments**
- Frontend/Backend integration with no errors
- the Recipes catalogue updates and creates without issue
- [Github Analytics](https://github.com/sarayu-pr11/tri2_pbl/graphs/contributors)
- ![image](https://user-images.githubusercontent.com/55467797/221641472-dc6897f1-ae03-4a81-9ced-902a3403eff2.png)

**Comment by PranaviInukurti** [comment]
SCORE: 18.5/20
Peer Grader #1 = Pranavi Inukurti

- N@TM  (5/5)
- Individual Runtime (4/5)
- delete function doesn't always work 
- Individual Code Review (5/5)
- Team Review Ticket (2/3)
- not sure about video/blogging/ReadMe work
- Individual Review Ticket (2.5/2)

**Comment by saumyapalk23** [comment]
SCORE: 9/10
Peer Grader = Saumya Palakodety
RUNTIME:
Project Quality = 1
UI Contains Inputs for validations = 1
UI contains actions for GET, POST, DELETE = 1
JWT Feature guarding = 1
CODE REVIEW:
Project Quality of Comments in Feature = 1
BE contains feature and API with error conditions = 1
BE has GET POST methods = 1
BE supports Create, Read = 1
BE supports Update, Delete = 0 -- DELETE doesn't always work, is faulty
