### ISSUE TITLE
Week 3: Backend Development, Sarayu Pochimireddy

### ISSUE THREAD

**Issue by sarayu-pr11** [sarayu-pr11/sarayucsa#5]
### Graded By: Samaya Sankuratri

[AWS Deployment](http://www.sarayu.tk/)
[Boolean If-else Lesson](https://sarayu-pr11.github.io/sarayucsa/jupyter/2022/09/07/week3.html)
[Focus and Habits](https://sarayu-pr11.github.io/sarayucsa/markdown/2022/09/11/gratitude.html)
[Resume](https://sarayu-pr11.github.io/sarayucsa/2022/09/12/resume.html)

**Comment by samayasankuratri** [comment]
### **Score: 2.7/3**
### **Graded by: Samaya Sankuratri**
AWS Deployment - Done and has linked their deployed page.
Boolean If-else Lesson - Has completed all the hacks and has used code blocks to show understanding of if and else.
Focus and Habits - Has watched the Yale video, taken notes, created gratitude list and gratitude notes.
Resume - Uploaded their resume on fastpages
