### ISSUE TITLE
Week 4 - Sarayu Pochimireddy

### ISSUE THREAD

**Issue by sarayu-pr11** [sarayu-pr11/sarayucsa#6]
**3/3 Graded by: Mr. Mortenson**
**2.7+/3 Graded by: Iris Yang**
[Fastpages](https://sarayu-pr11.github.io/sarayucsa/)
[College Board FRQ](https://sarayu-pr11.github.io/sarayucsa/jupyter/2022/09/13/apfrq.html)
[2D Array](https://sarayu-pr11.github.io/sarayucsa/jupyter/2022/09/15/2Darrays.html)
[Extra: Lesson Plan](https://sarayu-pr11.github.io/sarayucsa/markdown/2022/09/19/frqlesson.html)

**Comment by iriisyang** [comment]
2.7+/2.7
- FRQ complete thoroughly
- 2D Array print horizontally and change animals
- created lesson plan for methods and controls (frq)
