### ISSUE TITLE
Week 5: Design Starters

### ISSUE THREAD

**Issue by sarayu-pr11** [sarayu-pr11/sarayucsa#7]
# **Crossover Grade:** 
# **Teacher Grade:**
## [Fastpages](https://sarayu-pr11.github.io/sarayucsa/)
[Fibonacci](https://sarayu-pr11.github.io/sarayucsa/jupyter/2022/09/25/fibonaci.html)
*Javascript: ran into errors with the language not being available, so I did the work and pushed it as a post
[Javascript](https://sarayu-pr11.github.io/sarayucsa/jupyter/2022/09/25/javascript.html)
[Team Wireframes](https://sarayu-pr11.github.io/teamGrapeSnails/markdown/2022/09/23/pbl-plan.html)

**Comment by samayasankuratri** [comment]
**Score: 0.8/1**
Fibonacci - Completed the fibonacci hacks
Javascript - Does Not have the output displayed
Team Wireframes Completed
